Header header

geometry_msgs/Point pos_act
geometry_msgs/Vector3 euler_act
geometry_msgs/Twist vel_act

geometry_msgs/Point pos_des
geometry_msgs/Vector3 euler_des
geometry_msgs/Twist vel_des

float32 foot_force0_x
float32 foot_force0_y
float32 foot_force0_z
float32 foot_force1_x
float32 foot_force1_y
float32 foot_force1_z
float32 foot_force2_x
float32 foot_force2_y
float32 foot_force2_z
float32 foot_force3_x
float32 foot_force3_y
float32 foot_force3_z

float32 x_drag

float32 r_x_1
float32 r_x_2
float32 r_x_3
float32 r_x_4

float32 r_y_1
float32 r_y_2
float32 r_y_3
float32 r_y_4

float32 r_z_1
float32 r_z_2
float32 r_z_3
float32 r_z_4

float32 R_00
float32 R_01
float32 R_02

float32 R_10
float32 R_11
float32 R_12

float32 R_20
float32 R_21
float32 R_22


