# Static parameters fsm stand up for go1 sim
standup:
  Kp_joint0: 80
  Kp_joint1: 50
  Kp_joint2: 50

  Kd_joint0: 3
  Kd_joint1: 3
  Kd_joint2: 3

  Kp_cartesian_x: 1200
  Kp_cartesian_y: 1200
  Kp_cartesian_z: 1200

  Kd_cartesian_x: 35
  Kd_cartesian_y: 35
  Kd_cartesian_z: 55
